### PR TITLE
Fix NullReference in VolumeSeries if no data in Items list

### LINKED ISSUE #1491: NullReference in VolumeSeries if no data in Items list
**Steps to reproduce**
Create a new VolumeSeries object and add it to PlotModel.Series
```csharp
var plot = new PlotModel();
var volumeSeries = new VolumeSeries();
plot.Series.Add(volumeSeries);
// arrange Axes, add the plot to a form, etc.
```
Start the application
Platform:
Any

**Expected behaviour**
The plot is empty, only axes are shown 

**Actual behaviour**
NullReferenceException is thrown in VolumeSeries.UpdateData() method until you set VolumeSeries.Items property or add some data to it
oxyPlotVolumeSeriesNullRef

### PR DESCRIPTION
**Pull request by DShaurin**
Fixes #1491 .

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Add a check for item == null in VolumeSeries.GetNearestPoint and VolumeSeries.UpdateData methods

@oxyplot/admins

### CODE REVIEW

**Comment by Jonarw** [comment]
Thanks for your contribution!
Could you please update the changelog and list yourself in the CONTRIBUTORS file? Thanks!

File: Source/OxyPlot/Series/FinancialSeries/VolumeSeries.cs [hunk 1]
```diff
@@ -423,6 +423,11 @@ protected internal override void UpdateData()
             base.UpdateData();
             this.winIndex = 0;
 
+            if (this.data == null || this.data.Count == 0)
```
Comment (Jonarw) [inline Source/OxyPlot/Series/FinancialSeries/VolumeSeries.cs]: Are we changing behaviour here in case `data != null` and `data.Count == 0`? Previously it that case line 447 would have been run...

Comment (DShaurin) [reply Source/OxyPlot/Series/FinancialSeries/VolumeSeries.cs]: Yes, the UpdateData behavior is changed for this case, but it will have no effect on the plot since minDx is a gap size between existing bars. But, we have no bars at all if data.Count is 0, so minDx is not used.

**Comment by Jonarw** [comment]
Thanks!
