### PR TITLE
Double.Nan Linq.Min InvalidOperationException fix for #1991

### LINKED ISSUE #1991: System.InvalidOperationException: Sequence contains no elements when only dobule.NaN values are added to the LineSeries.
### Steps to reproduce

1. Add some `double.NaN` points to an empty line series (which is using smoothing).
2. Crash.

Platform.
.NET version: .NET 6

### Expected behaviour

The application should not crash, plot should stay unchanged.

### Actual behaviour

The application crashes with the following exception and stack trace
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Min[TSource](IEnumerable1 source, Func2 selector)
   at OxyPlot.Series.LineSeries.UpdateMaxMin() in C:\Users\Murdo\source\repos\oxyplot\Source\OxyPlot\Series\LineSeries.cs:line 426
   at OxyPlot.PlotModel.UpdateMaxMin(Boolean isDataUpdated) in C:\Users\Murdo\source\repos\oxyplot\Source\OxyPlot\PlotModel\PlotModel.cs:line 1171
   at OxyPlot.PlotModel.OxyPlot.IPlotModel.Update(Boolean updateData) in C:\Users\Murdo\source\repos\oxyplot\Source\OxyPlot\PlotModel\PlotModel.cs:line 801
```

### PR DESCRIPTION
**Pull request by rlamp**
Fixes #1991 .

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [X] I am listed in the CONTRIBUTORS file
- [X] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- The check whether to update Min/Max for a LineSeries must also include the filter for `double.Nan` values.

@oxyplot/admins

### CODE REVIEW

File: Source/OxyPlot/Series/LineSeries.cs [hunk 1]
```diff
@@ -410,7 +410,7 @@ protected internal override void UpdateMaxMin()
                 // Make sure the smooth points are re-evaluated.
                 this.ResetSmoothedPoints();
 
-                if (this.SmoothedPoints.Count == 0)
+                if (this.SmoothedPoints.Where(x => !double.IsNaN(x.X)).Count() == 0)
```
Comment (VisualMelon) [inline Source/OxyPlot/Series/LineSeries.cs]: I'd prefer `.All(x => double.IsNaN(x.X))`: bit easier to see what's going on, and will be faster in the usual case where there are values.

**Comment by VisualMelon** [comment]
Thanks for the bug report and fix! I don't have time to test this properly now, but shall try to do so in the next couple of days.

Apart from the comment above, the PR looks good pending testing.

File: Source/OxyPlot/Series/LineSeries.cs (hunk 1 above)
Comment (rlamp) [reply Source/OxyPlot/Series/LineSeries.cs]: Agree, changed it.
